export const CONFIG = {
  POSE_DETECTION_INTERVAL_MS: 150,
  MIN_KEYPOINT_CONFIDENCE: 0.4,
  CAMERA_QUALITY: 0.1,
  DEFAULT_DAILY_GOAL: 50,
  DAILY_REMINDER_HOUR: 9,
  EXPIRY_WARNING_MINUTES: 5,
  SCREEN_TIME_SAVED_FACTOR: 0.5,
};
